### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Sinetheta** [videojs/video.js-component#1]
Why is this in the bower repo? It's missing everything.

**Comment by heff** [comment]
What dependencies?

Here's the related discussion on the main repo: https://github.com/videojs/video.js/issues/381

**Comment by Sinetheta** [comment]
Looks like only the fonts are missing. Sorry, I didn't see that video-js is undergoing a lot of change, which would explain why this is a quick `/dist` dump.

**Comment by heff** [comment]
Ahhhhh...fonts...

**Comment by heff** [comment]
Added fonts and bumped the version. I think that should fix this issue.

**Comment by Sinetheta** [comment]
Yay, the short readme is a help too. I came here directly from bower and it looked more like someone's unmaintained fork than the popular project that video-js is. Thanks!
