### ISSUE TITLE
4.3.0 contains out of date video-js.dev.css

### ISSUE THREAD

**Issue by DeanMarkTaylor** [videojs/video.js-component#10]
It seems that `video-js.dev.css` should be removed?

**Comment by heff** [comment]
Yeah, looks like it should be since there's video-js.css and video-js.min.css. @dmlap or @bcjwilson, can you confirm that nothing's relying on that?

**Comment by gkatsev** [comment]
Nothing is relying on it. We added it originally to mimic the js file naming scheme since I don't think there was an unminified css file at the time.

**Comment by gkatsev** [comment]
No longer using this repo. And we're using more standard files names in 5.0.
