### ISSUE TITLE
documentation of release process

### ISSUE THREAD

**Issue by bcjwilson** [videojs/video.js-component#4]
Add to README Instructions on how to:
- build/copy latest video.js distributables into this repo,
- use git tag to mark release,
- publish to npm,
- publish to bower,
- announce the release.

Having these instructions in the README will enable anyone with rights to quickly take care of these tasks, and would facilitate automating them.

**Comment by heff** [comment]
Good idea.

I don't think there's a formal update process for bower. I think it happens through git tagging.

**Comment by gkatsev** [comment]
Yep, bower is 100% git/github based. It uses the tags to figure out
versions and stuff. And the bower.json file has the version as well.

**Comment by gkatsev** [comment]
We've moved away from using this repo. No more documentation necessary.
